### ISSUE TITLE
打包apk为release执行setGlobalLicense时应用崩溃

### ISSUE THREAD

**Issue by shi-lai-mu** [LiteAVSDK/Player_Flutter#117]
flutter 打包apk release后软件运行时，一旦触发 SuperPlayerPlugin.setGlobalLicense(LICENSE_URL, LICENSE_KEY) 会出现崩溃闪退，打包apk debug和开发环境下正常

adb log：
```shell
11-22 16:01:30.016 10834 10834 E GeneratedPluginRegistrant: Error registering plugin super_player, com.tencent.vod.flutter.SuperPlayerPlugin
11-22 16:01:30.016 10834 10834 E GeneratedPluginRegistrant:     at io.flutter.embedding.engine.c.g(Unknown Source:140)
11-22 16:01:30.016 10834 10834 E GeneratedPluginRegistrant:     at io.flutter.plugins.GeneratedPluginRegistrant.registerWith(Unknown Source:201)
11-22 16:01:30.016 10834 10834 E GeneratedPluginRegistrant:     at io.flutter.embedding.android.f.s(Unknown Source:9)
11-22 16:01:30.016 10834 10834 E GeneratedPluginRegistrant:     at io.flutter.embedding.android.g.s(Unknown Source:58)
11-22 16:01:30.016 10834 10834 E GeneratedPluginRegistrant:     at io.flutter.embedding.android.f.onCreate(Unknown Source:13)
11-22 16:01:30.413 10834 10834 F aier.studyskill: runtime.cc:691] "flutter-worker-0" prio=5 tid=18 TimedWaiting
11-22 16:01:30.413 10834 10834 F aier.studyskill: runtime.cc:691] "flutter-worker-1" prio=5 tid=19 TimedWaiting
11-22 16:01:30.413 10834 10834 F aier.studyskill: runtime.cc:691]   native: #03 pc 00460898  /data/app/~~fWNcGjbdwsOwZWliGUtUYw==/com.sig.study-ve8w8PPhsf3w65kYVzd3ag==/lib/arm64/libflutter.so (???) (BuildId: d9a7f562e5595e9913262ba4b5026a0df242ccfd)
11-22 16:01:30.413 10834 10834 F aier.studyskill: runtime.cc:691]   native: #04 pc 0045b9a0  /data/app/~~fWNcGjbdwsOwZWliGUtUYw==/com.sig.study-ve8w8PPhsf3w65kYVzd3ag==/lib/arm64/libflutter.so (???) (BuildId: d9a7f562e5595e9913262ba4b5026a0df242ccfd)
11-22 16:01:30.413 10834 10834 F aier.studyskill: runtime.cc:691]   native: #05 pc 007b9e7c  /data/app/~~fWNcGjbdwsOwZWliGUtUYw==/com.sig.study-ve8w8PPhsf3w65kYVzd3ag==/lib/arm64/libflutter.so (???) (BuildId: d9a7f562e5595e9913262ba4b5026a0df242ccfd)
11-22 16:01:30.413 10834 10834 F aier.studyskill: runtime.cc:691]   native: #06 pc 007aa868  /data/app/~~fWNcGjbdwsOwZWliGUtUYw==/com.sig.study-ve8w8PPhsf3w65kYVzd3ag==/lib/arm64/libflutter.so (???) (BuildId: d9a7f562e5595e9913262ba4b5026a0df242ccfd)
11-22 16:01:30.413 10834 10834 F aier.studyskill: runtime.cc:691]   native: #07 pc 0081fb90  /data/app/~~fWNcGjbdwsOwZWliGUtUYw==/com.sig.study-ve8w8PPhsf3w65kYVzd3ag==/lib/arm64/libflutter.so (???) (BuildId: d9a7f562e5595e9913262ba4b5026a0df242ccfd)
11-22 16:01:30.413 10834 10834 F aier.studyskill: runtime.cc:691]   native: #08 pc 007df980  /data/app/~~fWNcGjbdwsOwZWliGUtUYw==/com.sig.study-ve8w8PPhsf3w65kYVzd3ag==/lib/arm64/libflutter.so (???) (BuildId: d9a7f562e5595e9913262ba4b5026a0df242ccfd)
11-22 16:01:30.413 10834 10834 F aier.studyskill: runtime.cc:691]   native: #09 pc 007e03c0  /data/app/~~fWNcGjbdwsOwZWliGUtUYw==/com.sig.study-ve8w8PPhsf3w65kYVzd3ag==/lib/arm64/libflutter.so (???) (BuildId: d9a7f562e5595e9913262ba4b5026a0df242ccfd)
11-22 16:01:30.413 10834 10834 F aier.studyskill: runtime.cc:691]   native: #10 pc 007ca0e4  /data/app/~~fWNcGjbdwsOwZWliGUtUYw==/com.sig.study-ve8w8PPhsf3w65kYVzd3ag==/lib/arm64/libflutter.so (???) (BuildId: d9a7f562e5595e9913262ba4b5026a0df242ccfd)
11-22 16:01:30.413 10834 10834 F aier.studyskill: runtime.cc:691]   native: #22 pc 0085add4  /data/app/~~fWNcGjbdwsOwZWliGUtUYw==/com.sig.study-ve8w8PPhsf3w65kYVzd3ag==/lib/arm64/libflutter.so (???) (BuildId: d9a7f562e5595e9913262ba4b5026a0df242ccfd)
11-22 16:01:30.413 10834 10834 F aier.studyskill: runtime.cc:691]   native: #23 pc 0099abe0  /data/app/~~fWNcGjbdwsOwZWliGUtUYw==/com.sig.study-ve8w8PPhsf3w65kYVzd3ag==/lib/arm64/libflutter.so (???) (BuildId: d9a7f562e5595e9913262ba4b5026a0df242ccfd)
11-22 16:01:30.413 10834 10834 F aier.studyskill: runtime.cc:691]   native: #24 pc 007c3ac8  /data/app/~~fWNcGjbdwsOwZWliGUtUYw==/com.sig.study-ve8w8PPhsf3w65kYVzd3ag==/lib/arm64/libflutter.so (???) (BuildId: d9a7f562e5595e9913262ba4b5026a0df242ccfd)
11-22 16:01:30.413 10834 10834 F aier.studyskill: runtime.cc:691]   native: #25 pc 00475abc  /data/app/~~fWNcGjbdwsOwZWliGUtUYw==/com.sig.study-ve8w8PPhsf3w65kYVzd3ag==/lib/arm64/libflutter.so (???) (BuildId: d9a7f562e5595e9913262ba4b5026a0df242ccfd)
11-22 16:01:30.413 10834 10834 F aier.studyskill: runtime.cc:691]   native: #26 pc 00479698  /data/app/~~fWNcGjbdwsOwZWliGUtUYw==/com.sig.study-ve8w8PPhsf3w65kYVzd3ag==/lib/arm64/libflutter.so (???) (BuildId: d9a7f562e5595e9913262ba4b5026a0df242ccfd)
11-22 16:01:30.413 10834 10834 F aier.studyskill: runtime.cc:691]   native: #29 pc 004797a4  /data/app/~~fWNcGjbdwsOwZWliGUtUYw==/com.sig.study-ve8w8PPhsf3w65kYVzd3ag==/lib/arm64/libflutter.so (???) (BuildId: d9a7f562e5595e9913262ba4b5026a0df242ccfd)
11-22 16:01:30.413 10834 10834 F aier.studyskill: runtime.cc:691]   native: #30 pc 00477808  /data/app/~~fWNcGjbdwsOwZWliGUtUYw==/com.sig.study-ve8w8PPhsf3w65kYVzd3ag==/lib/arm64/libflutter.so (???) (BuildId: d9a7f562e5595e9913262ba4b5026a0df242ccfd)
11-22 16:01:30.413 10834 10834 F aier.studyskill: runtime.cc:691]   native: #31 pc 004775fc  /data/app/~~fWNcGjbdwsOwZWliGUtUYw==/com.sig.study-ve8w8PPhsf3w65kYVzd3ag==/lib/arm64/libflutter.so (???) (BuildId: d9a7f562e5595e9913262ba4b5026a0df242ccfd)

```

**Comment by Kongdy** [comment]
参考官网文档常见问题第 11 条，补充混淆配置即可：
https://cloud.tencent.com/document/product/881/81252#.E5.B8.B8.E8.A7.81.E9.97.AE.E9.A2.98
