### ISSUE TITLE
集成之后app调用 setGlobalLicense native崩溃

### ISSUE THREAD

**Issue by guuguo** [LiteAVSDK/Player_Flutter#85]
这是看到的JAVA报错，看起来是setGlobalLicense方法抛出的异常：
```
runtime.cc:675]   at java.lang.Runtime.nativeLoad(Runtime.java:1121)
runtime.cc:675]   at java.lang.Runtime.loadLibrary0(Runtime.java:1075)
runtime.cc:675]   - locked <0x0af5543f> (a java.lang.Runtime)
runtime.cc:675]   at java.lang.Runtime.loadLibrary0(Runtime.java:998)
runtime.cc:675]   at java.lang.System.loadLibrary(System.java:1661)
runtime.cc:675]   at x0.d.b(SourceFile:45)
runtime.cc:675]   at x0.d.a(SourceFile:30)
runtime.cc:675]   - locked <0x01da410c> (a java.lang.Object)
runtime.cc:675]   at l1.e.<clinit>(SourceFile:35)
runtime.cc:675]   at l1.e.a(SourceFile:44)
runtime.cc:675]   at z2.l.h(SuperPlayerPlugin.java:207)
runtime.cc:675]   at a3.e1.w(FtxMessages.java:2603)
runtime.cc:675]   at a3.e1.f(FtxMessages.java:0)
runtime.cc:675]   at a3.z0.onMessage(unavailable:2)
runtime.cc:675]   at io.flutter.plugin.common.BasicMessageChannel$IncomingMessageHandler.onMessage(BasicMessageChannel.java:217)
runtime.cc:675]   at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:295)
runtime.cc:675]   at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0(DartMessenger.java:322)
runtime.cc:675]   at io.flutter.embedding.engine.dart.DartMessenger.a(unavailable:0)
runtime.cc:675]   at io.flutter.embedding.engine.dart.a.run(unavailable:12)
```
这是Flutter报错信息：
```
[GETX] Instance "GlobalLogic" has been created
W/SoLoader(30688): load library txsoundtouch from system path 
W/SoLoader(30688): load library txsoundtouch true
W/SoLoader(30688): load library txffmpeg from system path 
W/SoLoader(30688): load library txffmpeg true
W/SoLoader(30688): load library liteavsdk from system path 
E/liteav  (30688): [E][05-11/21:28:42.878+8.0][30688,30688][jni_android.cc:148]Failed to find class com/tencent/liteav/base/JNIUtils
F/com.maofan.app(30688): java_vm_ext.cc:594] JNI DETECTED ERROR IN APPLICATION: GetStaticMethodID received NULL jclass
F/com.maofan.app(30688): java_vm_ext.cc:594]     in call to GetStaticMethodID
F/com.maofan.app(30688): java_vm_ext.cc:594]     from java.lang.String java.lang.Runtime.nativeLoad(java.lang.String, java.lang.ClassLoader, java.lang.Class)
```

**Comment by Kongdy** [comment]
@guuguo 看log是没有加载成功so，建议使用 flutter dotocr 对本地环境进行检查，修复其中的问题项。并执行
flutter clean 
flutter pub get
删除项目下的 build 文件夹
然后重新安装试试

**Comment by Kongdy** [comment]
长时间未回复，问题关闭

**Comment by guuguo** [comment]
@Kongdy 多次尝试无法解决问题。clean doctor 都正常，看打包后的 app也包含需要so库。 现在已经放弃该 sdk用别的。😂

**Comment by guuguo** [comment]
之前好好的，结果改了一下安卓包名又出现了setGlobalLicense  崩溃。改回来之后依然崩溃。
