### ISSUE TITLE
在红米k40上总是会把屏幕变得很暗

### ISSUE THREAD

**Issue by hpp0hpp** [LiteAVSDK/Player_Flutter#90]
我hook了几个函数,怀疑是获取最大亮度出了问题

```
Hook getBrightnessMax()
        return 8191
Hook getSystemScreenBrightness()
        return 0.00317421555519104

Hook setWindowBrightness(java.lang.Double)
        arg0 = 0.00317421555519104
java.lang.Exception
        at com.tencent.vod.flutter.SuperPlayerPlugin.setWindowBrightness(Native Method)
        at com.tencent.vod.flutter.SuperPlayerPlugin.access$100(SuperPlayerPlugin.java:60)
        at com.tencent.vod.flutter.SuperPlayerPlugin$2.onChange(SuperPlayerPlugin.java:100)
        at android.database.ContentObserver.onChange(ContentObserver.java:224)
        at android.database.ContentObserver.lambda$dispatchChange$0$android-database-ContentObserver(ContentObserver.java:304)
        at android.database.ContentObserver$$ExternalSyntheticLambda0.run(Unknown Source:10)
        at android.os.Handler.handleCallback(Handler.java:942)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loopOnce(Looper.java:210)
        at android.os.Looper.loop(Looper.java:299)
        at android.app.ActivityThread.main(ActivityThread.java:8261)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:559)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:954)

        return undefined

```

```
adb shell "dumpsys power | grep ScreenBrightness"
  mLastScreenBrightnessBoostTime=0 (445922118 ms ago)
  mScreenBrightnessBoostInProgress=false
  mDozeScreenBrightnessOverrideFromDreamManager=-1
  mScreenBrightnessMinimum=7.32601E-4
  mScreenBrightnessMaximum=1.0
  mScreenBrightnessDefault=0.07484738

```

**Comment by hpp0hpp** [comment]
注释掉这行解决问题了
![image](https://github.com/LiteAVSDK/Player_Flutter/assets/54829297/349def81-3765-4de3-b33f-b3f177c1e606)

**Comment by Kongdy** [comment]
@hpp0hpp MIUI在14.0之后，获取的最大亮度值与实际不符，最新版本已经做了兼容，可以更新最新版本验证
